# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone settings
timezone: America/New_York

# jekyll-seo-tag settings
title: Smart Solution LLC
tagline: Our Github Pages Site! (work in progress)
description: Description in progress

# Site URL settings
url: "https://smart-solution-llc.github.io"

github:
  username: Smart-Solution-LLC

twitter:
  username: twitter_username

social:
  name: Nick Moffitt
  email: Nick@SmartSolutions518.com
  links:
    - https://twitter.com/smart_sol_518
    - https://github.com/smart_solution_llc
    - https://www.facebook.com/smartsolutions518
    - https://www.linkedin.com/in/smartsolutionllc

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

# Pageviews settings
pageviews:
  provider: # now only supports 'goatcounter'

# Theme mode settings
theme_mode: # [light | dark]

# CDN endpoint for media resources
cdn:

# Sidebar avatar settings
avatar:

# Social preview image for SEO
social_preview_image:

# Global Table of Contents (TOC) settings
toc: true

# Comments system settings
comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname: # fill with the Disqus shortname
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets settings
assets:
  self_host:
    enabled: # boolean, keep empty means false
    env: # [development | production]

# Progressive Web App (PWA) settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

# Pagination settings
paginate: 10

# Base URL of your site
baseurl: ""

# Kramdown settings for Markdown processing
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections settings
collections:
  tabs:
    output: true
    sort_by: order

# Default settings for various scopes
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Sass compression settings
sass:
  style: compressed

# HTML compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Exclude files from the build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

# Jekyll Archives settings
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
